### ISSUE TITLE
{"score":{"raw":0}} gets sent as {"score":[]} 

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#34] opened 2015-06-10 19:51 UTC
@ryansmih94 reported that {"score":{"raw":0}} gets sent as {"score":[]} 

I've not tested myself.

**Comment by brianjmiller** [comment] 2015-11-18 20:31
I'm not able to reproduce this, but added #43 which should be correct to test it and prevent regression. Thoughts?

**Comment by garemoko** [comment] 2015-11-18 20:56
That sounds like a sensible approach to me. @ryansmith94 do you want to re-test with the latest version?

**Comment by brianjmiller** [comment] 2015-11-19 02:23
I merged #43 so going to close this, obviously if you spot it again and can reproduce feel free to re-open or open a new one.

**Closed by brianjmiller** 2015-11-19 02:23 UTC
Labels: invalid

**Comment by ryansmith94** [comment] 2015-11-19 09:02
Sounds good, will do @brianjmiller thanks :+1:
